apiVersion: v1
entries:
  dataexplorer:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-05-27T10:40:50.154702017+02:00"
    dependencies:
    - name: library-chart
      repository: https://inseefrlab.github.io/helm-charts-interactive-services
      version: 1.5.21
    description: A Helm chart for Kubernetes
    digest: 341ee8f6d33d44b1d86fad4dcdfb2de45531aace1f6d2d818f529d1f2ac377ed
    name: dataexplorer
    type: application
    urls:
    - https://afredojala.github.io/onyx-helmcharts/charts/dataexplorer-0.1.2.tgz
    version: 0.1.2
  vscode-python:
  - apiVersion: v2
    created: "2024-05-27T10:40:50.155686882+02:00"
    dependencies:
    - name: library-chart
      repository: https://inseefrlab.github.io/helm-charts-interactive-services
      version: 1.5.21
    description: The Visual Studio Code IDE with Python, Julia, and a collection of
      standard data science packages.
    digest: 302a5dbb839a1b6cda3893fd0caa3a880818ab30cd60e6573ebe249a96df53f6
    icon: https://minio.lab.sspcloud.fr/projet-onyxia/assets/servicesImg/vscode.png
    keywords:
    - VSCode
    - Python
    name: vscode-python
    type: application
    urls:
    - https://afredojala.github.io/onyx-helmcharts/charts/vscode-python-1.11.32.tgz
    version: 1.11.32
generated: "2024-05-27T10:40:50.151411288+02:00"
